#ifndef WWW_FILES_H_
#define WWW_FILES_H_

// THIS FILE IS AUTOMATICALLY GENERATED.
// MODIFY sources/mkCfiles.py INSTEAD OF THIS.




struct Www_file {
	const char * filename;
	const int * filesize;
	const char * content;
	const int cacheable;
};

extern const struct Www_file www_files[17];
extern const int num_files;

#endif
